#!/bin/sh

make -j4 ; 
echo "------Make Finished------"
make uImage;
echo "------uImage Finished------"
cp arch/arm/boot/uImage /tftpboot/;
cp arch/arm/boot/uImage ../../output/kernel/;
echo "------Finished------"
