#
# Makefile for the Aspeed network device driver.
#

#obj-$(CONFIG_ASTMAC100)     += ftgmac100.o
obj-$(CONFIG_ASTMAC100)     += ast_gmac.o
obj-$(CONFIG_ASTMAC100)     += dev-eth.o
obj-$(CONFIG_LEGACY_ASTMAC100)     += ast_ether.o
