#
# Makefile for the linux kernel.
#

# Object file lists.

obj-y					:= setup.o irq.o time.o
obj-$(CONFIG_SOC_AST3100)		+= usbhost.o
obj-$(CONFIG_SOC_AST3200)		+= usbhost.o
obj-$(CONFIG_PCIE_AST)                  += ast_p2x.o
